# Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true

# App
VERSION_NAME=1.0
VERSION_CODE=1

# Kotlin Multiplatform
kotlin.native.ignoreDisabledTargets=true

# Windows performance/locking fixes
org.gradle.vfs.watch=false
